### PR TITLE
Fix crash when rendering graphviz svg

### LINKED ISSUE #13: Graphviz SVGs cause exception
(@szacchino Moved your issue to the library that's causing the error)

---

Hi,

trying with several SVG as generated by dot/graphviz (i.e.: https://graphviz.gitlab.io/_pages/Gallery/directed/cluster.svg) causes the following exception

```
/usr/local/lib/node_modules/coarse-cli/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:206
          throw new DOMException("The object can not be found here.", "NotFoundError");
          ^
NotFoundError: The object can not be found here.
    at SVGSVGElementImpl.insertBefore (/usr/local/lib/node_modules/coarse-cli/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:206:17)
    at SVGSVGElementImpl.replaceChild (/usr/local/lib/node_modules/coarse-cli/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:269:10)
    at SVGSVGElement.replaceChild (/usr/local/lib/node_modules/coarse-cli/node_modules/jsdom/lib/jsdom/living/generated/Node.js:307:45)
    at coarse (/usr/local/lib/node_modules/coarse-cli/node_modules/coarse/lib/index.js:102:11)
    at fn (/usr/local/lib/node_modules/coarse-cli/bin/index.js:71:32)
    at Object.<anonymous> (/usr/local/lib/node_modules/coarse-cli/bin/index.js:75:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
```

I've just used `coarse <input> <output>` without any further options.

---

Moved from https://github.com/ismay/coarse-cli/issues/2

### PR DESCRIPTION
**Pull request by ismay**
Closes #13

### CODE REVIEW

**Comment by ismay** [comment]
@szacchino So I'm not sure why, but using `replaceWith` instead of `replaceChild` seems to fix the error. Don't know if this is a jsdom bug, or whether I'm just doing something wrong.

Could you try whether this patch works as expected for you?

**Comment by ismay** [comment]
This is what I'm getting with the svg you supplied, looks good to me:

screen shot 2018-07-23 at 11 58 55

**Comment by szacchino** [comment]
Great...

Thank you very much! :)

immagine

**Comment by ismay** [comment]
Cool, you’re welcome! 👍

**Pull request merged**
